---
title: "Introduction aux réseaux spatiaux avec R"
#author: "[Maxime Lenormand](https://www.maximelenormand.com/)"
url: 'https://github.com/ML-Teaching/Spatial-Networks'
description: "Réseaux spatiaux"
favicon: "assets/favicon.ico"
bibliography: "refs/references.bib"
csl: "refs/references.csl"
---

# Préambule {.unnumbered #preambule}

Bienvenue dans ce module sur les **réseaux spatiaux** avec **R**. Ce module vous 
propose une exploration approfondie des réseaux spatiaux, et plus particulièrement 
des **interactions spatiales**, à travers l’utilisation des packages 
**TDLM** [[@Lenormand2023]](#refs) et 
**bioregion** [[@Denelle2025]](#refs). 

Vous apprendrez à utiliser :

- [**R**](https://www.r-project.org/), 
[**RStudio**](https://posit.co/download/rstudio-desktop/) et 
[**Shiny**](https://shiny.posit.co/) en abordant des notions de base pour 
manipuler des données et pour créer des applications interactives simples avec 
le package **Shiny** [[@Shiny]](#refs) pour visualiser et explorer vos réseaux 
spatiaux de manière dynamique.

- **[TDLM](https://rtdlm.github.io/TDLM/)** en comparant rigoureusement 
différentes lois de distribution des déplacements (telles que la loi de gravité 
ou de radiation) et en modélisant les flux de déplacements 
entre zones géographiques avec différents niveaux de contraintes.

- **[bioregion](https://biorgeo.github.io/bioregion/)** en appliquant des 
méthodes de biorégionalisation pour identifier des unités spatiales homogènes en
termes de composition d'espèces, en utilisant des algorithmes de clustering 
hiérarchique, non hiérarchique et des méthodes issues de la théorie des réseaux.

Ce **GitBook** est conçu pour être à la fois un **support théorique** et un 
**guide pratique** : chaque concept sera accompagné d’exemples directement 
applicables dans **R** grâce aux packages 
[TDLM](https://rtdlm.github.io/TDLM/) et 
[bioregion](https://biorgeo.github.io/bioregion/).

Avant d’entrer dans le détail des TPs, voici une 
introduction générale aux réseaux spatiaux. Elle présente les concepts clés, 
le vocabulaire essentiel ainsi que le programme du module.

<div style="height:10px;">&nbsp;</div>

<iframe src="slides/intro/Cours_Introduction.pdf" width="100%" height="450px"></iframe>

<div style="height:10px;">&nbsp;</div>

L’ensemble des ressources citées dans ce GitBook est regroupé dans la section 
**[Références](#refs)**. Vous y trouverez également plusieurs ouvrages et 
publications de référence : 
[@Barabasi2016](#refs), 
[@Barthelemy2011](#refs), 
[@Barbosa2018](#refs)
ou encore 
[@Barthelemy2023](#refs).




